version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: thursday
      timezone: Asia/Tokyo
    commit-message:
      prefix: "deps"
    reviewers:
      - high-moctane
    ignore:
      - dependency-name: "go"
      - dependency-name: "toolchain"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    reviewers:
      - high-moctane
    open-pull-requests-limit: 5
